# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  environment.systemPackages = with pkgs; [
    vim
    falkon
    wget
    virtualbox
    kate
    yakuake
    calligra
    plasma-nm 
    git
  ];

  programs.bash.enableCompletion = true;

  # broadcom wifi driver
  nixpkgs.config.allowUnfree = true;

}
